name: Linting

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  terraform-fmt:
    name: 'Terraform Format (Lint)'
    runs-on: ubuntu-latest
    steps:

    # git clone repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install the latest (fully opensource) version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # Moves *.tf files to root directory to prepare for linting
    - name: Run the script
      run: |
        ./deploy-tf.sh -f

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Linting (Terraform Format)
      run: terraform fmt -check
